print("                ./oyhhhhhhhhhhys/-                ")
print("            .+hhs/-`           ./ohho-            ")
print("         `+dy/`                     :sdo.         ")
print("       .sm+`                           /dy-       ")
print("     `om/                                :dy`     ")
print("    -ms`                                   +N/    ")
print("   /N:                                      -mo   ")
print("  +N-                                        .ms  ")
print(" :M-               \          /               .N+ ")
print("`mo                 \        /                 /M.")
print("+N`                   Aliens                    ds")
print("dy                  /        \                  +N")
print("N+                 /**********\                 :M")
print("mo                                              /M")
print("sd                                              yd")
print(".M:                                            .M/")
print(" sm`   :/:.                            `--.    hh ")
print(" `ds  dMm/:+y/`                     :s++oNMo  +N. ")
print("  .N+ hMMhymMMMy-                .sNMMhoyMMy :N-  ")
print("   -N+.NMMMMMMMMMd-            -hMMMMMMMMMm.:N:   ")
print("    -m+.hMMMMMMMMMMs`        `sMMMMMMMMMMh.:N:    ")
print("     .ms /mMMMMMMMMMd       `dMMMMMMMMMm/ +m-     ")
print("      `yh` :yNMMMMMMM/      oMMMMMMMMh/  sd.      ")
print("        +m:   -oydmms`      -dMMNds/`  .ds        ")
print("         .ds`           -``           od-         ")
print("           +d/         /o-y         :do           ")
print("            `oh:                  -hy.            ")
print("              `oh/   `ohddho`   :ys.              ")
print("                 /ys:        -oy+`                ")
print("                   `/ssssssss/.                   ")
print()
aliens = 2
password = "Aliens"
print("Quickly! Aliens are invading the planet.")
print("You need to activate the global defence platforms.")
print("Hope you know the password, for Earth's sake...")
print()
print("--------------------------------------------------")
print("        WELCOME TO THE GLOBAL DEFENCE NETWORK     ")
print("--------------------------------------------------")
print()
guess = input("Please enter the password: ")
while guess != password:
    print()
    print("INCORRECT PASSWORD.")
    print()
    aliens = aliens ** 2
    print("The are", aliens, "aliens now on Earth. Try again!")
    if aliens > 7400000000:
        break
    print()
    print("Password hint: the things that are attacking us.")
    print()
    guess = input("Quick! Please enter the password: ")
if aliens > 7400000000:
    print("Nooooo! The aliens have outnumbered us. All is lost.")
else:
    print("Hooray! We won the figth and the world saved!")
